### PR TITLE
fix(notification): fix icon alignment for multiline message

### PR DESCRIPTION
**Pull request by dine**

### CODE REVIEW

**Review by bartderijk — DISMISSED** [review]
What Connor said, +approved :)

**Comment by ConnorChristensen** [comment]
Is this new abstraction of the ui-icon-type an internal only change, or is this also a feature that should be used by other projects?

**Comment by dine** [comment]
image

I could add some stories for the ui-icon-type too

**Comment by ConnorChristensen** [comment]
I am ok with it either way, but if we do, I think it should be a feature rather than a fix and I would recommend removing the required margin right around the icon to make incorporating it into different designs more flexible.

**Review by bartderijk — APPROVED** [review]

**Pull request merged**
