### PR TITLE
Remove ui prefix

### PR DESCRIPTION
**Pull request by bartderijk**
Following the bi-weekly call to remove the pre-fix, I adjusted the code base accordingly.

### CODE REVIEW

**Review by dine — APPROVED** [review]

**Review by daniarsuprianto — COMMENTED** [review]
Are we going to do this also for all projects with tailwind in the end?

**Comment by dine** [comment]
@daniarsuprianto I think it's safe, funda-ui has a different prefix ('fd-') and the chances of class names collision seem to be low in our projects, as we didn't use to do many functional classes there. Do you have concerns?

**Comment by daniarsuprianto** [comment]
@dine nothing, i was just wondering because last time we discussed about the ui- prefix, and now we changed without prefix.. so just curious why and what's the reason. i dont see there'll be any conflict or whatsoever with current projects because other than funda-ui utilities classes, we dont work 'utility-first'

**Review by daniarsuprianto — APPROVED** [review]

**Comment by renancarvalho** [comment]
NICE! no more ui-!
Good!

**Review by renancarvalho — APPROVED** [review]
-

**Review by larsdouweschuitema — APPROVED** [review]

**Comment by larsdouweschuitema** [comment]
Thanks for the work on this @bartderijk

**Pull request merged**
